# Importing Libraries

In [67]:
#Importing Libraries
import pandas as pd
import numpy as np

# Data Collection

In [68]:
#Data Collection
da=pd.read_csv('Automobile price data _Raw_.csv')

# Data Understanding

In [69]:
#Data Understanding - Data Understanding/DQ Report
da.head(30)

symboling normalized-losses         make fuel-type aspiration  \
0           3                 ?  alfa-romero       gas        std   
1           3                 ?  alfa-romero       gas        std   
2           1                 ?  alfa-romero       gas        std   
3           2               164         audi       gas        std   
4           2               164         audi       gas        std   
5           2                 ?         audi       gas        std   
6           1               158         audi       gas        std   
7           1                 ?         audi       gas        std   
8           1               158         audi       gas      turbo   
9           0                 ?         audi       gas      turbo   
10          2               192          bmw       gas        std   
11          0               192          bmw       gas        std   
12          0               188          bmw       gas        std   
13          0               188          bmw       gas        std   
14          1                 ?          bmw       gas        std   
15          0                 ?          bmw       gas        std   
16          0                 ?          bmw       gas        std   
17          0                 ?          bmw       gas        std   
18          2               121    chevrolet       gas        std   
19          1                98    chevrolet       gas        std   
20          0                81    chevrolet       gas        std   
21          1               118        dodge       gas        std   
22          1               118        dodge       gas        std   
23          1               118        dodge       gas      turbo   
24          1               148        dodge       gas        std   
25          1               148        dodge       gas        std   
26          1               148        dodge       gas        std   
27          1               148        dodge       gas      turbo   
28         -1               110        dodge       gas        std   
29          3               145        dodge       gas      turbo   

   num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0           two  convertible          rwd           front        88.6  ...   
1           two  convertible          rwd           front        88.6  ...   
2           two    hatchback          rwd           front        94.5  ...   
3          four        sedan          fwd           front        99.8  ...   
4          four        sedan          4wd           front        99.4  ...   
5           two        sedan          fwd           front        99.8  ...   
6          four        sedan          fwd           front       105.8  ...   
7          four        wagon          fwd           front       105.8  ...   
8          four        sedan          fwd           front       105.8  ...   
9           two    hatchback          4wd           front        99.5  ...   
10          two        sedan          rwd           front       101.2  ...   
11         four        sedan          rwd           front       101.2  ...   
12          two        sedan          rwd           front       101.2  ...   
13         four        sedan          rwd           front       101.2  ...   
14         four        sedan          rwd           front       103.5  ...   
15         four        sedan          rwd           front       103.5  ...   
16          two        sedan          rwd           front       103.5  ...   
17         four        sedan          rwd           front       110.0  ...   
18          two    hatchback          fwd           front        88.4  ...   
19          two    hatchback          fwd           front        94.5  ...   
20         four        sedan          fwd           front        94.5  ...   
21          two    hatchback          fwd           front        93.7  ...   
22          two    hatchback          fwd           front        93.7 

# Data Cleaning

In [132]:
#Data Cleaning
da.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    float64
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    int64  
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

In [116]:

da.describe()

symboling  normalized-losses  num-of-doors  wheel-base      length  \
count  205.000000         205.000000    205.000000  205.000000  205.000000   
mean     0.834146         117.120000      3.131707   98.756585  174.049268   
std      1.245307          33.157365      0.993715    6.021776   12.337289   
min     -2.000000          65.000000      2.000000   86.600000  141.100000   
25%      0.000000          97.600000      2.000000   94.500000  166.300000   
50%      1.000000         103.000000      4.000000   97.000000  173.200000   
75%      2.000000         137.000000      4.000000  102.400000  183.100000   
max      3.000000         256.000000      4.000000  120.900000  208.100000   

            width      height  curb-weight  engine-size  compression-ratio  \
count  205.000000  205.000000   205.000000   205.000000         205.000000   
mean    65.907805   53.724878  2555.565854   126.907317          10.142537   
std      2.145204    2.443522   520.680204    41.642693           3.972040   
min     60.300000   47.800000  1488.000000    61.000000           7.000000   
25%     64.100000   52.000000  2145.000000    97.000000           8.600000   
50%     65.500000   54.100000  2414.000000   120.000000           9.000000   
75%     66.900000   55.500000  2935.000000   141.000000           9.400000   
max     72.300000   59.800000  4066.000000   326.000000          23.000000   

       horsepower     peak-rpm    city-mpg  highway-mpg         price  
count  205.000000   205.000000  205.000000   205.000000    205.000000  
mean   104.246234  5124.881618   25.219512    30.751220  13202.101059  
std     39.519338   477.004538    6.542142     6.886443   7868.849339  
min     48.000000  4150.000000   13.000000    16.000000   5118.000000  
25%     70.000000  4800.000000   19.000000    25.000000   7788.000000  
50%     95.000000  5200.000000   24.000000    30.000000  10595.000000  
75%    116.000000  5500.000000   30.000000    34.000000  16500.000000  
max    288.000000  6600.000000   49.000000    54.000000  45400.000000

In [72]:
da.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

### Normalised losses

In [73]:
da['normalized-losses'].loc[da['normalized-losses']=='?'].count()

41

In [74]:
da['normalized-losses']=da['normalized-losses'].replace('?',0)

In [75]:
da['normalized-losses']=pd.to_numeric(da['normalized-losses'])


In [76]:
da['normalized-losses']=da['normalized-losses'].replace(0,da['normalized-losses'].mean())

In [77]:
da['make'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [78]:
da.head()

symboling  normalized-losses         make fuel-type aspiration  \
0          3               97.6  alfa-romero       gas        std   
1          3               97.6  alfa-romero       gas        std   
2          1               97.6  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19    3.40              10.0        102   
4          136         mpfi  3.19    3.40               8.0        115   

   peak-rpm city-mpg highway-mpg  price  
0      5000       21          27  13495  
1      5000       21          27  16500  
2      5000       19          26  16500  
3      5500       24          30  13950  
4      5500       18          22  17450  

[5 rows x 26 columns]

### Number of Doors

In [79]:
da['num-of-doors'].unique()

array(['two', 'four', '?'], dtype=object)

In [83]:
da['num-of-doors']=da['num-of-doors'].replace({'four':4,'two':2,'?':4})

In [84]:
da['num-of-doors'].head()

0    2
1    2
2    2
3    4
4    4
Name: num-of-doors, dtype: int64

In [85]:
da['num-of-doors']=pd.to_numeric(da['num-of-doors'])

In [86]:
da['num-of-doors'].loc[da['num-of-doors']=='?'].count()

0

### Price

In [95]:
da['price'].str.isnumeric().value_counts()

True     201
False      4
Name: price, dtype: int64

In [96]:
da['price']=da['price'].replace('?',0)

In [97]:
da['price']=pd.to_numeric(da['price'])

In [98]:
da['price']=da['price'].replace(0,da['price'].mean())

In [102]:
da['price'].dtype

dtype('float64')

### Peak RPM

In [105]:
da['peak-rpm'].str.isnumeric().value_counts()

True     203
False      2
Name: peak-rpm, dtype: int64

In [106]:
da['peak-rpm']=da['peak-rpm'].replace('?',0)

In [107]:
da['peak-rpm']=pd.to_numeric(da['peak-rpm'])

In [108]:
da['peak-rpm']=da['peak-rpm'].replace(0,da['peak-rpm'].mean())

In [109]:
da['peak-rpm'].head()

0    5000.0
1    5000.0
2    5000.0
3    5500.0
4    5500.0
Name: peak-rpm, dtype: float64

### HorsePower

In [110]:
da['horsepower'].str.isnumeric().value_counts()

True     203
False      2
Name: horsepower, dtype: int64

In [111]:
da['horsepower']=da['horsepower'].replace('?',0)

In [112]:
da['horsepower']=pd.to_numeric(da['horsepower'])

In [113]:
da['horsepower']=da['horsepower'].replace(0,da['horsepower'].mean())

In [150]:
da.loc[da['horsepower']>10000]

Empty DataFrame
Columns: [symboling, normalized-losses, make, fuel-type, aspiration, num-of-doors, body-style, drive-wheels, engine-location, wheel-base, length, width, height, curb-weight, engine-type, num-of-cylinders, engine-size, fuel-system, bore, stroke, compression-ratio, horsepower, peak-rpm, city-mpg, highway-mpg, price]
Index: []

[0 rows x 26 columns]

### Bore

In [119]:
da['bore'].str.isnumeric().value_counts()

False    205
Name: bore, dtype: int64

In [120]:
da['bore']=da['bore'].replace('?',0)

In [121]:
da['bore']=pd.to_numeric(da['bore'])

In [122]:
da['bore']=da['bore'].replace(da['bore'].mean())

In [123]:
da['bore']

0      3.47
1      3.47
2      2.68
3      3.19
4      3.19
       ... 
200    3.78
201    3.78
202    3.58
203    3.01
204    3.78
Name: bore, Length: 205, dtype: float64

### Stroke

In [125]:
da['stroke'].str.isnumeric().value_counts()

False    205
Name: stroke, dtype: int64

In [128]:
da['stroke']=da['stroke'].replace('?',0)

In [129]:
da['stroke']=pd.to_numeric(da['stroke'])

In [130]:
da['stroke']=da['stroke'].replace(0,da['stroke'].mean())

In [131]:
da['stroke']

0      2.68
1      2.68
2      3.47
3      3.40
4      3.40
       ... 
200    3.15
201    3.15
202    2.87
203    3.40
204    3.15
Name: stroke, Length: 205, dtype: float64

In [161]:
da.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    float64
 2   make               205 non-null    int64  
 3   fuel-type          205 non-null    int64  
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    int64  
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    int64  
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    int64  
 15  num-of-cylinders   205 non-null    int64  
 16  engine-size        205 non

### Number of cylinders

In [141]:
#Encoding - To convert any alphabte data into numbers
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

da['num-of-cylinders'] = le.fit_transform(da['num-of-cylinders'])


### Fuel System

In [142]:
da['fuel-system']

0      5
1      5
2      5
3      5
4      5
      ..
200    5
201    5
202    5
203    3
204    5
Name: fuel-system, Length: 205, dtype: int64

### Engine type 

In [147]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
da['engine-type']=le.fit_transform(da['engine-type'])
print(da['engine-type'])

0      0
1      0
2      5
3      3
4      3
      ..
200    3
201    3
202    5
203    3
204    3
Name: engine-type, Length: 205, dtype: int64


In [151]:
da.head()

symboling  normalized-losses         make fuel-type aspiration  \
0          3               97.6  alfa-romero       gas        std   
1          3               97.6  alfa-romero       gas        std   
2          1               97.6  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

   num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0             2  convertible          rwd           front        88.6  ...   
1             2  convertible          rwd           front        88.6  ...   
2             2    hatchback          rwd           front        94.5  ...   
3             4        sedan          fwd           front        99.8  ...   
4             4        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke  compression-ratio  horsepower  \
0          130            5  3.47    2.68                9.0       111.0   
1          130            5  3.47    2.68                9.0       111.0   
2          152            5  2.68    3.47                9.0       154.0   
3          109            5  3.19    3.40               10.0       102.0   
4          136            5  3.19    3.40                8.0       115.0   

   peak-rpm  city-mpg  highway-mpg    price  
0    5000.0        21           27  13495.0  
1    5000.0        21           27  16500.0  
2    5000.0        19           26  16500.0  
3    5500.0        24           30  13950.0  
4    5500.0        18           22  17450.0  

[5 rows x 26 columns]

### Engine Location

In [153]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
da['engine-location']=le.fit_transform(da['engine-location'])
print(da['engine-location'])

0      0
1      0
2      0
3      0
4      0
      ..
200    0
201    0
202    0
203    0
204    0
Name: engine-location, Length: 205, dtype: int64


### Make

In [155]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
da['make']=le.fit_transform(da['make'])
print(da['make'])

0       0
1       0
2       0
3       1
4       1
       ..
200    21
201    21
202    21
203    21
204    21
Name: make, Length: 205, dtype: int64


### Fuel Type

In [160]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
da['fuel-type']=le.fit_transform(da['fuel-type'])
da['fuel-type']

0      1
1      1
2      1
3      1
4      1
      ..
200    1
201    1
202    1
203    0
204    1
Name: fuel-type, Length: 205, dtype: int64

### Aspiration

In [162]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
da['aspiration']=le.fit_transform(da['aspiration'])
da['aspiration']

0      0
1      0
2      0
3      0
4      0
      ..
200    0
201    1
202    0
203    1
204    1
Name: aspiration, Length: 205, dtype: int64

In [164]:
da.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    float64
 2   make               205 non-null    int64  
 3   fuel-type          205 non-null    int64  
 4   aspiration         205 non-null    int64  
 5   num-of-doors       205 non-null    int64  
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    int64  
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    int64  
 15  num-of-cylinders   205 non-null    int64  
 16  engine-size        205 non

### Body Style

In [166]:
bs_bods = pd.get_dummies(da['body-style'])
print(bs_bods)

     convertible  hardtop  hatchback  sedan  wagon
0              1        0          0      0      0
1              1        0          0      0      0
2              0        0          1      0      0
3              0        0          0      1      0
4              0        0          0      1      0
..           ...      ...        ...    ...    ...
200            0        0          0      1      0
201            0        0          0      1      0
202            0        0          0      1      0
203            0        0          0      1      0
204            0        0          0      1      0

[205 rows x 5 columns]


In [167]:
#One-Hot Encoding for Location
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
bs_bodystyle = lb.fit_transform(da['body-style'])
print(bs_bodystyle)

[[1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 ...
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]]


In [168]:
da = pd.concat([da,bs_bods], axis = 1)

In [169]:
del da['body-style']

In [170]:
da.head()

symboling  normalized-losses  make  fuel-type  aspiration  num-of-doors  \
0          3               97.6     0          1           0             2   
1          3               97.6     0          1           0             2   
2          1               97.6     0          1           0             2   
3          2              164.0     1          1           0             4   
4          2              164.0     1          1           0             4   

  drive-wheels  engine-location  wheel-base  length  ...  horsepower  \
0          rwd                0        88.6   168.8  ...       111.0   
1          rwd                0        88.6   168.8  ...       111.0   
2          rwd                0        94.5   171.2  ...       154.0   
3          fwd                0        99.8   176.6  ...       102.0   
4          4wd                0        99.4   176.6  ...       115.0   

   peak-rpm  city-mpg  highway-mpg    price  convertible  hardtop  hatchback  \
0    5000.0        21           27  13495.0            1        0          0   
1    5000.0        21           27  16500.0            1        0          0   
2    5000.0        19           26  16500.0            0        0          1   
3    5500.0        24           30  13950.0            0        0          0   
4    5500.0        18           22  17450.0            0        0          0   

   sedan  wagon  
0      0      0  
1      0      0  
2      0      0  
3      1      0  
4      1      0  

[5 rows x 30 columns]

### Drive Wheels

In [177]:
dr_w=pd.get_dummies(da['drive-wheels'])
print(dr_w)

     4wd  fwd  rwd
0      0    0    1
1      0    0    1
2      0    0    1
3      0    1    0
4      1    0    0
..   ...  ...  ...
200    0    0    1
201    0    0    1
202    0    0    1
203    0    0    1
204    0    0    1

[205 rows x 3 columns]


In [178]:
from sklearn.preprocessing import LabelBinarizer
lb=LabelBinarizer()
dr_wheel=lb.fit_transform(da['drive-wheels'])
da['drive-wheels']

0      rwd
1      rwd
2      rwd
3      fwd
4      4wd
      ... 
200    rwd
201    rwd
202    rwd
203    rwd
204    rwd
Name: drive-wheels, Length: 205, dtype: object

In [180]:
da=pd.concat([da,dr_w] , axis=1)

In [181]:
del da['drive-wheels']

In [182]:
da.head()

symboling  normalized-losses  make  fuel-type  aspiration  num-of-doors  \
0          3               97.6     0          1           0             2   
1          3               97.6     0          1           0             2   
2          1               97.6     0          1           0             2   
3          2              164.0     1          1           0             4   
4          2              164.0     1          1           0             4   

   engine-location  wheel-base  length  width  ...  highway-mpg    price  \
0                0        88.6   168.8   64.1  ...           27  13495.0   
1                0        88.6   168.8   64.1  ...           27  16500.0   
2                0        94.5   171.2   65.5  ...           26  16500.0   
3                0        99.8   176.6   66.2  ...           30  13950.0   
4                0        99.4   176.6   66.4  ...           22  17450.0   

   convertible  hardtop  hatchback  sedan  wagon  4wd  fwd  rwd  
0            1        0          0      0      0    0    0    1  
1            1        0          0      0      0    0    0    1  
2            0        0          1      0      0    0    0    1  
3            0        0          0      1      0    0    1    0  
4            0        0          0      1      0    1    0    0  

[5 rows x 32 columns]

In [183]:
da.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 32 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    float64
 2   make               205 non-null    int64  
 3   fuel-type          205 non-null    int64  
 4   aspiration         205 non-null    int64  
 5   num-of-doors       205 non-null    int64  
 6   engine-location    205 non-null    int64  
 7   wheel-base         205 non-null    float64
 8   length             205 non-null    float64
 9   width              205 non-null    float64
 10  height             205 non-null    float64
 11  curb-weight        205 non-null    int64  
 12  engine-type        205 non-null    int64  
 13  num-of-cylinders   205 non-null    int64  
 14  engine-size        205 non-null    int64  
 15  fuel-system        205 non-null    int64  
 16  bore               205 non

# Splitting the data into input/output 

In [184]:
#Splitting data into IP/OP
y=da['price']

In [186]:
X=da.drop(['price'], axis=1)

In [187]:
y.head()

0    13495.0
1    16500.0
2    16500.0
3    13950.0
4    17450.0
Name: price, dtype: float64

# You split the data into Train Data & Test Data - Scikit-Learn

In [261]:
#You split the data into Train Data & Test Data - Scikit-Learn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_n,y , test_size = 0.2, random_state = 1022)
print(X_train.shape)
print(X_test.shape)


(164, 31)
(41, 31)


# Training the model

In [262]:
#Training the Model
from sklearn import linear_model #Parametric Model
from sklearn.tree import DecisionTreeRegressor #Non-Parametric Model
#Calling the algorithm/Model/estimator
model = linear_model.LinearRegression()
#model = DecisionTreeRegressor()
model.fit(X_train,y_train)

LinearRegression()

# Test The Model

In [263]:
#Test The Model
predicted = model.predict(X_test)
predicted

array([ 2439.79285675,  7924.75147309, 19148.99789489,  9448.43386385,
       11018.86515988,  7775.9224684 , 11644.76481726, 16862.40881397,
        7756.18157611, 13993.28684918,  9158.22331677,  8343.95709947,
       22512.06448534, 11241.35966065, 11492.76414578,  5369.81353356,
       14993.63597367,  7667.82038149, 14834.46463316,  6155.03446198,
       11437.12392541,  9317.85966374, 17981.55348967, 10220.89402121,
        6302.65240446, 38626.27324129, 10765.74826401, 12335.54585935,
       24251.67092606, 10474.72904904,  8457.61535658, 17789.76536865,
       12589.90697578, 10128.54575008,  7747.13168178, 11796.65500646,
       17408.84158615, 20064.81006006, 13020.23580356, 18814.52389487,
       20908.3096381 ])

# Evaluate the model

In [265]:
#Evaluate the Model
from sklearn.metrics import mean_squared_error, r2_score
print(r2_score(y_test, predicted)) #Coefficient of Determination

0.8777853389934854


# Feature Scaling

### Standard Scaler

In [192]:
#Accuracy Improving Methods
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)

In [193]:
X_std

array([[ 1.74347043, -0.59014897, -1.94825569, ..., -0.21428571,
        -1.18817705,  1.30283093],
       [ 1.74347043, -0.59014897, -1.94825569, ..., -0.21428571,
        -1.18817705,  1.30283093],
       [ 0.133509  , -0.59014897, -1.94825569, ..., -0.21428571,
        -1.18817705,  1.30283093],
       ...,
       [-1.47645244, -0.66875488,  1.40664061, ..., -0.21428571,
        -1.18817705,  1.30283093],
       [-1.47645244, -0.66875488,  1.40664061, ..., -0.21428571,
        -1.18817705,  1.30283093],
       [-1.47645244, -0.66875488,  1.40664061, ..., -0.21428571,
        -1.18817705,  1.30283093]])

### Normalizer

In [198]:
from sklearn.preprocessing import Normalizer
#fit command maintainss the equation structure
X_n = Normalizer().fit_transform(X)


In [199]:
X_n

array([[ 0.00053389,  0.01736908,  0.        , ...,  0.        ,
         0.        ,  0.00017796],
       [ 0.00053389,  0.01736908,  0.        , ...,  0.        ,
         0.        ,  0.00017796],
       [ 0.00017389,  0.01697144,  0.        , ...,  0.        ,
         0.        ,  0.00017389],
       ...,
       [-0.00015924,  0.01512787,  0.00334405, ...,  0.        ,
         0.        ,  0.00015924],
       [-0.0001728 ,  0.01641639,  0.00362889, ...,  0.        ,
         0.        ,  0.0001728 ],
       [-0.00016088,  0.01528392,  0.00337855, ...,  0.        ,
         0.        ,  0.00016088]])